springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: pool-challenge
      uri: mongodb+srv://admin:admin@cluster0.mmz1f.mongodb.net/?retryWrites=true&w=majority
